// <auto-generated />
using Leilao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leilao.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201030220314_InitialDatabase2")]
    partial class InitialDatabase2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Leilao.Models.PessoaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Leilao.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ULTIMOLANCE")
                        .HasColumnType("float");

                    b.Property<int>("UlTIMAPESSOAID")
                        .HasColumnType("int");

                    b.Property<double>("VALOR")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("UlTIMAPESSOAID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Leilao.Models.ProdutoModel", b =>
                {
                    b.HasOne("Leilao.Models.PessoaModel", "ULTIMAPESSOA")
                        .WithMany("produtos")
                        .HasForeignKey("UlTIMAPESSOAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
